@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "cpf": "777.777.777.77",
  "password": "111111"
}

###

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "David Leonardeli",
  "cpf": "777.777.777.77.11111",
  "password": "111111",
  "type": "EMPLOYEE"
}

###

# @name create_recipient
POST {{baseUrl}}/recipients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Fulano 5",
  "cpf": "555.555.555.55"
}

###

# @name register_recipient_address
POST {{baseUrl}}/recipients/bf04f25e-e62c-4124-896b-38d2a6c8a0d8/addresses
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "country": "Brasil",
  "state": "Santa Catarina",
  "city": "Ararangua",
  "neighborhood": "Mato Alto",
  "street": "Amaro José Pereira",
  "number": 222
}

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "description": "Controle",
  "recipientId": "bf04f25e-e62c-4124-896b-38d2a6c8a0d8",
  "addressId": "38a4a50e-c20d-4995-81dd-5c213d1fa4e3"
}

###

# @name read_notification
PATCH {{baseUrl}}/notifications/33ac0b08-6068-4a41-9b83-fe69391b9310/read
Content-Type: application/json

{
  "userCpf": "121.111.111.10"
}

###

# @name asign_order_to_carrier
PATCH {{baseUrl}}/orders/1eada74e-6e53-477c-b1d2-d442c6d09c64/asign-carrier
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name return_package
PATCH {{baseUrl}}/orders/eae70bf5-22b6-4ef4-80a5-1c90d3d9c36a/return
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_near_orders
GET {{baseUrl}}/nearOrders?neighborhood=Coloninha
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name alter_user_password
PATCH {{baseUrl}}/users/5d9319b7-d56e-4b35-9735-56605e88eb9b/alter-password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "newUserPassword": "999"
}

###

# @name fetch_user_orders
GET {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name fetch_single_user
GET {{baseUrl}}/users/31dae27b-7711-41c2-955e-e31e1d8e1811
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name fetch_single_order
GET {{baseUrl}}/orders/1eada74e-6e53-477c-b1d2-d442c6d09c64
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name delete_user
DELETE {{baseUrl}}/users/c71cf61b-4734-4f97-b4b6-681fb14940bd
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name fetch_list_user
GET {{baseUrl}}/list-of-orders?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name fetch_list_orders
GET {{baseUrl}}/orders?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name fetch_recipient_addresses
GET {{baseUrl}}/addresses/bf04f25e-e62c-4124-896b-38d2a6c8a0d8
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name edit_user
PUT {{baseUrl}}/users/edit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "newUserCpf": "123.456.789.10",
  "newUserName": "Thobias de Souza Maciel"
}

### 

# @name deliver_package
PATCH {{baseUrl}}/orders/cfccb747-212b-467c-aff1-b926b3db6770/deliver
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="orderId"

cfccb747-212b-467c-aff1-b926b3db6770
--BOUNDARY
Content-Disposition: form-data; name="deliveredAt"

2026-02-18T10:30:00Z
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="package.png"
Content-Type: image/png

< ./package.png
--BOUNDARY--

###

# @name list_of_orders
GET {{baseUrl}}/list-of-orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_order
PUT {{baseUrl}}/orders/cfccb747-212b-467c-aff1-b926b3db6770/edit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "newOrderDescription": "Tijolos amarelos"
}

### 

# @name delete_order
DELETE {{baseUrl}}/orders/cfccb747-212b-467c-aff1-b926b3db6770
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name list_of_recipients
GET {{baseUrl}}/list-of-recipients
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_recipient
PUT {{baseUrl}}/recipients/de54955f-f063-46e0-b1e3-62d2c6882115/edit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "newRecipientCpf": "987.654.321.00",
  "newRecipientName": "Dominus"
}

### 

# @name delete_recipient
DELETE {{baseUrl}}/recipients/de54955f-f063-46e0-b1e3-62d2c6882115
Content-Type: application/json
Authorization: Bearer {{authToken}}